const devices = [
  {
    id: 'WS-BDO-001',
    apiKey: 'ws-bandung-001-key',
    fw: '1.4.2',
    baseBattery: 3.92,
    baseRssi: -71,
    location: 'Bandung',
    timezone: 'Asia/Jakarta',
    sensorRanges: {
      temp_air: { min: 22, max: 34 },
      humidity: { min: 50, max: 95 },
      pressure: { min: 1005, max: 1015 },
      wind_speed: { min: 0, max: 12 },
      wind_dir: { min: 0, max: 359 },
      rain_counter: { start: 1043, incrementPerMinute: 0.1 },
      solar_rad: { min: 0, max: 800 },
    },
  },
  {
    id: 'JKT-BMKG-001',
    apiKey: 'ws-jakarta-001-key',
    fw: '1.4.2',
    baseBattery: 4.05,
    baseRssi: -65,
    location: 'Jakarta',
    timezone: 'Asia/Jakarta',
    sensorRanges: {
      temp_air: { min: 24, max: 35 },
      humidity: { min: 55, max: 92 },
      pressure: { min: 1006, max: 1014 },
      wind_speed: { min: 0, max: 10 },
      wind_dir: { min: 0, max: 359 },
      rain_counter: { start: 2087, incrementPerMinute: 0.15 },
      solar_rad: { min: 0, max: 850 },
    },
  },
  {
    id: 'SBY-PLN-001',
    apiKey: 'ws-surabaya-001-key',
    fw: '1.3.8',
    baseBattery: 3.45,
    baseRssi: -85,
    location: 'Surabaya',
    timezone: 'Asia/Jakarta',
    sensorRanges: {
      temp_air: { min: 25, max: 36 },
      humidity: { min: 45, max: 88 },
      pressure: { min: 1004, max: 1013 },
      wind_speed: { min: 0, max: 15 },
      wind_dir: { min: 0, max: 359 },
      rain_counter: { start: 512, incrementPerMinute: 0.05 },
      solar_rad: { min: 0, max: 900 },
    },
    simulateError: true,
  },
];

export default devices;
